services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env   # pakai env dari folder Server
    restart: always

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always
